package frame;

import tela3.LocarVeiculoTableModel;
import tela3.Locacao;
import tela3.FiltroDeTabela;
import java.awt.Point;
import java.awt.event.MouseEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.ToolTipManager;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import tela1.*;
import tela2.*;
import tela3.ClienteLocacaoTableModel;
import tela4.VeiculoDevolverTableModel;
import tela5.VeiculoVenderTableModel;

public class Frame extends javax.swing.JFrame {

    private Main main;
    private ClienteTableModel ctm;
    private LocarVeiculoTableModel lvtm;
    private ClienteLocacaoTableModel cltm;
    private VeiculoDevolverTableModel vdtm;
    private VeiculoVenderTableModel vvtm;

    private Repository rep;
    private ComboModels cm;
    private FiltroDeTabela f, f1;

    public Frame() {
        rep = new Repository();
        ctm = new ClienteTableModel();
        lvtm = new LocarVeiculoTableModel();
        cltm = new ClienteLocacaoTableModel();
        vdtm = new VeiculoDevolverTableModel();
        vvtm = new VeiculoVenderTableModel();
        ctm.repRef(rep);
        lvtm.repRef(rep);
        cltm.repRef(rep);
        vdtm.repRef(rep);
        vvtm.repRef(rep);
        cm = new ComboModels();

        initComponents();

        f = new FiltroDeTabela();
        f.criarTabela(veiculoTable);
        f1 = new FiltroDeTabela();
        f1.criarTabela(VendaTable);

        ClienteLocacaoTableModel modelcl = (ClienteLocacaoTableModel) clienteLocacaoTable.getModel();
        modelcl.setSingleSelection(clienteLocacaoTable);
        LocarVeiculoTableModel modellv = (LocarVeiculoTableModel) veiculoTable.getModel();
        modellv.setSingleSelection(veiculoTable);
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabbedPane = new javax.swing.JTabbedPane();
        tabCliente = new javax.swing.JPanel();
        nomeCliente = new javax.swing.JLabel();
        sobrenomeCliente = new javax.swing.JLabel();
        rgCliente = new javax.swing.JLabel();
        cpfCliente = new javax.swing.JLabel();
        enderecoCliente = new javax.swing.JLabel();
        TFnome = new javax.swing.JTextField();
        TFsobrenome = new javax.swing.JTextField();
        TFrg = new javax.swing.JFormattedTextField();
        TFcpf = new javax.swing.JFormattedTextField();
        TFendereco = new javax.swing.JTextField();
        BincluirCliente = new javax.swing.JButton();
        BlistarCliente = new javax.swing.JButton();
        BremoverCliente = new javax.swing.JButton();
        BlimparCliente = new javax.swing.JButton();
        BatualizarCliente = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        clienteTable = new javax.swing.JTable();
        Pveiculos = new javax.swing.JPanel();
        BincluirVeiculo = new javax.swing.JButton();
        LvalorDaCompra = new javax.swing.JLabel();
        Lplaca = new javax.swing.JLabel();
        Lmodelo = new javax.swing.JLabel();
        Lmarca = new javax.swing.JLabel();
        Ccategoria = new javax.swing.JComboBox<>();
        Lcategoria = new javax.swing.JLabel();
        Lano = new javax.swing.JLabel();
        Ctipo = new javax.swing.JComboBox<>();
        Cmodelo = new javax.swing.JComboBox<>();
        Cmarca = new javax.swing.JComboBox<>();
        Ltipo = new javax.swing.JLabel();
        Cestado = new javax.swing.JComboBox<>();
        Lestado = new javax.swing.JLabel();
        FTFplaca = new javax.swing.JFormattedTextField();
        FTFano = new javax.swing.JFormattedTextField();
        FTFvalorDeCompra = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        Bvans = new javax.swing.JButton();
        Bmotocicletas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        veiculoTable = new javax.swing.JTable();
        Bautomoveis = new javax.swing.JButton();
        CmarcaVeiculos = new javax.swing.JComboBox<>();
        CcategoriaVeiculos = new javax.swing.JComboBox<>();
        TFpesquisa = new javax.swing.JTextField();
        Blocar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        clienteLocacaoTable = new javax.swing.JTable();
        LpesquisarClientes = new javax.swing.JLabel();
        FTFdataLocacao = new javax.swing.JFormattedTextField();
        LnumDiasLocacao = new javax.swing.JLabel();
        LdataLocacao = new javax.swing.JLabel();
        TFdiasLocacao = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        DevolverTable = new javax.swing.JTable();
        BvansDevolver = new javax.swing.JButton();
        BmotocicletasDevolver = new javax.swing.JButton();
        BautomoveisDevolver = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        VendaTable = new javax.swing.JTable();
        CcategoriaVeiculosVenda = new javax.swing.JComboBox<>();
        CmarcaVeiculosVenda = new javax.swing.JComboBox<>();
        BautomoveisVenda = new javax.swing.JButton();
        BmotocicletasVenda = new javax.swing.JButton();
        BvansVenda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TabbedPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        nomeCliente.setText("Nome");

        sobrenomeCliente.setText("Sobrenome");

        rgCliente.setText("RG");

        cpfCliente.setText("CPF");

        enderecoCliente.setText("Endereço");

        TFnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFnomeActionPerformed(evt);
            }
        });

        try {
            TFrg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            TFcpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TFcpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFcpfActionPerformed(evt);
            }
        });

        BincluirCliente.setText("Incluir");
        BincluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BincluirClienteActionPerformed(evt);
            }
        });

        BlistarCliente.setText("Listar");
        BlistarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlistarClienteActionPerformed(evt);
            }
        });

        BremoverCliente.setText("Remover");
        BremoverCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BremoverClienteActionPerformed(evt);
            }
        });

        BlimparCliente.setText("Limpar");
        BlimparCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlimparClienteActionPerformed(evt);
            }
        });

        BatualizarCliente.setText("Atualizar");
        BatualizarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BatualizarClienteActionPerformed(evt);
            }
        });

        clienteTable.setModel(ctm);
        jScrollPane2.setViewportView(clienteTable);
        clienteTable.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent event) {
                // Verifique se há uma linha selecionada
                if (clienteTable.getSelectedRow() != -1) {
                    // Obtenha o valor da célula na coluna que você está interessado
                    Object nome = clienteTable.getValueAt(clienteTable.getSelectedRow(), 0); // Altere o 0 para o índice da coluna que você deseja
                    Object sobrenome = clienteTable.getValueAt(clienteTable.getSelectedRow(), 1);
                    Object rg = clienteTable.getValueAt(clienteTable.getSelectedRow(), 2);
                    Object cpf = clienteTable.getValueAt(clienteTable.getSelectedRow(), 3);
                    Object endereco = clienteTable.getValueAt(clienteTable.getSelectedRow(), 4);
                    // Defina o valor no JTextField
                    TFnome.setText(nome.toString());
                    TFsobrenome.setText(sobrenome.toString());
                    TFrg.setText(rg.toString());
                    TFcpf.setText(cpf.toString());
                    TFendereco.setText(endereco.toString());

                }
            }
        });

        javax.swing.GroupLayout tabClienteLayout = new javax.swing.GroupLayout(tabCliente);
        tabCliente.setLayout(tabClienteLayout);
        tabClienteLayout.setHorizontalGroup(
            tabClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabClienteLayout.createSequentialGroup()
                .addGroup(tabClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(tabClienteLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(tabClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cpfCliente, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(enderecoCliente, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(sobrenomeCliente, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(tabClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TFendereco)
                                    .addComponent(TFsobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabClienteLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(TFcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(tabClienteLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(nomeCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addComponent(TFnome, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabClienteLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(rgCliente)
                            .addGap(18, 18, 18)
                            .addComponent(TFrg, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(tabClienteLayout.createSequentialGroup()
                        .addGroup(tabClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(tabClienteLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(BincluirCliente)
                                .addGap(18, 18, 18)
                                .addComponent(BatualizarCliente))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tabClienteLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(BremoverCliente)))
                        .addGap(53, 53, 53)
                        .addGroup(tabClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BlistarCliente)
                            .addComponent(BlimparCliente))))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(154, Short.MAX_VALUE))
        );
        tabClienteLayout.setVerticalGroup(
            tabClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabClienteLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(tabClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabClienteLayout.createSequentialGroup()
                        .addGroup(tabClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TFnome, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomeCliente))
                        .addGap(17, 17, 17)
                        .addGroup(tabClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TFsobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sobrenomeCliente))
                        .addGap(18, 18, 18)
                        .addGroup(tabClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TFrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rgCliente))
                        .addGap(18, 18, 18)
                        .addGroup(tabClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TFcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cpfCliente))
                        .addGap(18, 18, 18)
                        .addGroup(tabClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TFendereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enderecoCliente))
                        .addGroup(tabClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabClienteLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(tabClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BincluirCliente)
                                    .addComponent(BatualizarCliente)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabClienteLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BlistarCliente)))
                        .addGroup(tabClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabClienteLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(BremoverCliente))
                            .addGroup(tabClienteLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(BlimparCliente))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(141, 141, 141))
        );

        TabbedPane.addTab("Clientes", tabCliente);

        Pveiculos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Pveiculos.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                PveiculosComponentShown(evt);
            }
        });

        BincluirVeiculo.setText("Incluir");
        BincluirVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BincluirVeiculoActionPerformed(evt);
            }
        });

        LvalorDaCompra.setText("valor de compra");

        Lplaca.setText("placa");

        Lmodelo.setText("modelo");

        Lmarca.setText("marca");

        Ccategoria.setModel(cm.getCategoriaModel());
        Ccategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CcategoriaActionPerformed(evt);
            }
        });

        Lcategoria.setText("categoria");

        Lano.setText("ano");

        Ctipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Motocicleta", "Automóvel", "Van" }));
        Ctipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CtipoActionPerformed(evt);
            }
        });

        Cmodelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmodeloActionPerformed(evt);
            }
        });

        Cmarca.setModel(cm.getMarcaModel());
        Cmarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmarcaActionPerformed(evt);
            }
        });

        Ltipo.setText("tipo");

        Cestado.setModel(cm.getEstadoModel());

        Lestado.setText("estado");

        try {
            FTFplaca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("UUU-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        FTFano.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("####"))));

        javax.swing.GroupLayout PveiculosLayout = new javax.swing.GroupLayout(Pveiculos);
        Pveiculos.setLayout(PveiculosLayout);
        PveiculosLayout.setHorizontalGroup(
            PveiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PveiculosLayout.createSequentialGroup()
                .addGroup(PveiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PveiculosLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(PveiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PveiculosLayout.createSequentialGroup()
                                .addGroup(PveiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Lmodelo)
                                    .addComponent(Ltipo)
                                    .addComponent(Lestado))
                                .addGroup(PveiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PveiculosLayout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addGroup(PveiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Cmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Ctipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(26, 26, 26)
                                        .addGroup(PveiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(PveiculosLayout.createSequentialGroup()
                                                .addComponent(Lmarca)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(Cmarca, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(PveiculosLayout.createSequentialGroup()
                                                .addComponent(Lcategoria)
                                                .addGap(12, 12, 12)
                                                .addComponent(Ccategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(PveiculosLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(Cestado, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(PveiculosLayout.createSequentialGroup()
                                .addGroup(PveiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LvalorDaCompra)
                                    .addGroup(PveiculosLayout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addGroup(PveiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Lano)
                                            .addComponent(Lplaca))))
                                .addGroup(PveiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PveiculosLayout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addGroup(PveiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(FTFplaca, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(FTFano, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(PveiculosLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(FTFvalorDeCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(PveiculosLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(BincluirVeiculo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PveiculosLayout.setVerticalGroup(
            PveiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PveiculosLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(PveiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ctipo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lmarca)
                    .addComponent(Cmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ltipo))
                .addGap(18, 18, 18)
                .addGroup(PveiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PveiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Ccategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Lcategoria))
                    .addGroup(PveiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Cmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Lmodelo)))
                .addGap(36, 36, 36)
                .addGroup(PveiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lestado)
                    .addComponent(Cestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PveiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LvalorDaCompra)
                    .addComponent(FTFvalorDeCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PveiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lplaca)
                    .addComponent(FTFplaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PveiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lano)
                    .addComponent(FTFano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(BincluirVeiculo)
                .addContainerGap(293, Short.MAX_VALUE))
        );

        TabbedPane.addTab("Veículos", Pveiculos);

        jPanel3.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel3ComponentShown(evt);
            }
        });

        Bvans.setText("Vans");
        Bvans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BvansActionPerformed(evt);
            }
        });

        Bmotocicletas.setText("Motocicletas");
        Bmotocicletas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BmotocicletasActionPerformed(evt);
            }
        });

        veiculoTable.setModel(lvtm);
        veiculoTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                veiculoTableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(veiculoTable);

        Bautomoveis.setText("Automoveis");
        Bautomoveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BautomoveisActionPerformed(evt);
            }
        });

        CmarcaVeiculos.setModel(cm.getMarcaLocacaoModel());
        CmarcaVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmarcaVeiculosActionPerformed(evt);
            }
        });

        CcategoriaVeiculos.setModel(cm.getCategoriaLocacaoModel());
        CcategoriaVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CcategoriaVeiculosActionPerformed(evt);
            }
        });

        TFpesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFpesquisaActionPerformed(evt);
            }
        });
        TFpesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TFpesquisaKeyReleased(evt);
            }
        });

        Blocar.setText("Locar");
        Blocar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlocarActionPerformed(evt);
            }
        });

        clienteLocacaoTable.setModel(cltm);
        jScrollPane3.setViewportView(clienteLocacaoTable);

        LpesquisarClientes.setText("Pesquisar Clientes");

        try {
            FTFdataLocacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        FTFdataLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FTFdataLocacaoActionPerformed(evt);
            }
        });

        LnumDiasLocacao.setText("numDiasLocacao");

        LdataLocacao.setText("data");

        try {
            TFdiasLocacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(LpesquisarClientes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TFpesquisa))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(LnumDiasLocacao)
                                .addGap(33, 33, 33))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(LdataLocacao)
                                .addGap(43, 43, 43)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(TFdiasLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(126, 126, 126)
                                .addComponent(Blocar))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(FTFdataLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(46, 46, 46)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(Bvans)
                        .addGap(72, 72, 72)
                        .addComponent(Bmotocicletas)
                        .addGap(18, 18, 18)
                        .addComponent(Bautomoveis)
                        .addGap(38, 38, 38)
                        .addComponent(CmarcaVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(CcategoriaVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(107, 107, 107))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bvans)
                    .addComponent(Bmotocicletas)
                    .addComponent(Bautomoveis)
                    .addComponent(CmarcaVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CcategoriaVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LpesquisarClientes))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(121, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Blocar)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(LnumDiasLocacao)
                                .addComponent(TFdiasLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FTFdataLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LdataLocacao))
                        .addGap(54, 54, 54))))
        );

        TabbedPane.addTab("Locação", jPanel3);

        jPanel4.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel4ComponentShown(evt);
            }
        });

        DevolverTable.setModel(vdtm);
        DevolverTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DevolverTableMousePressed(evt);
            }
        });
        jScrollPane5.setViewportView(DevolverTable);

        BvansDevolver.setText("Vans");
        BvansDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BvansDevolverActionPerformed(evt);
            }
        });

        BmotocicletasDevolver.setText("Motocicletas");
        BmotocicletasDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BmotocicletasDevolverActionPerformed(evt);
            }
        });

        BautomoveisDevolver.setText("Automoveis");
        BautomoveisDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BautomoveisDevolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(351, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(BvansDevolver)
                        .addGap(28, 28, 28)
                        .addComponent(BmotocicletasDevolver)
                        .addGap(18, 18, 18)
                        .addComponent(BautomoveisDevolver)
                        .addGap(231, 231, 231)))
                .addGap(270, 270, 270))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BvansDevolver)
                    .addComponent(BmotocicletasDevolver)
                    .addComponent(BautomoveisDevolver))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        TabbedPane.addTab("Devolução", jPanel4);

        VendaTable.setModel(vvtm);
        VendaTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                VendaTableMousePressed(evt);
            }
        });
        jScrollPane4.setViewportView(VendaTable);

        CcategoriaVeiculosVenda.setModel(cm.getCategoriaLocacaoModel());
        CcategoriaVeiculosVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CcategoriaVeiculosVendaActionPerformed(evt);
            }
        });

        CmarcaVeiculosVenda.setModel(cm.getMarcaLocacaoModel());
        CmarcaVeiculosVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmarcaVeiculosVendaActionPerformed(evt);
            }
        });

        BautomoveisVenda.setText("Automoveis");
        BautomoveisVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BautomoveisVendaActionPerformed(evt);
            }
        });

        BmotocicletasVenda.setText("Motocicletas");
        BmotocicletasVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BmotocicletasVendaActionPerformed(evt);
            }
        });

        BvansVenda.setText("Vans");
        BvansVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BvansVendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(370, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(BvansVenda)
                        .addGap(28, 28, 28)
                        .addComponent(BmotocicletasVenda)
                        .addGap(18, 18, 18)
                        .addComponent(BautomoveisVenda)
                        .addGap(38, 38, 38)
                        .addComponent(CmarcaVeiculosVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(CcategoriaVeiculosVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(251, 251, 251))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BvansVenda)
                    .addComponent(BmotocicletasVenda)
                    .addComponent(BautomoveisVenda)
                    .addComponent(CmarcaVeiculosVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CcategoriaVeiculosVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        TabbedPane.addTab("Venda", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(TabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1338, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFnomeActionPerformed

    private void BincluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BincluirClienteActionPerformed
        String nome = TFnome.getText();
        String sobrenome = TFsobrenome.getText();
        String rg = TFrg.getText();
        String cpf = TFcpf.getText();
        String endereco = TFendereco.getText();
        Cliente cliente = new Cliente(nome, sobrenome, rg, cpf, endereco);
        ctm.addCliente(cliente);
        TFnome.setText("");
        TFsobrenome.setText("");
        TFrg.setText("");
        TFcpf.setText("");
        TFendereco.setText("");


    }//GEN-LAST:event_BincluirClienteActionPerformed

    private void BlistarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlistarClienteActionPerformed
        ctm.setListaCliente();
        for (Cliente c : rep.getListaClientes()) {//test
            System.out.print(c.getNome());
        }//test

    }//GEN-LAST:event_BlistarClienteActionPerformed

    private void BremoverClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BremoverClienteActionPerformed

        if (clienteTable.getSelectedRow() == -1) {
            BremoverCliente.setToolTipText("Selecione um ou mais clientes para remover.");
            // Força o tooltip a aparecer imediatamente
            ToolTipManager.sharedInstance().setInitialDelay(0);
            // Cria um evento de mouse falso para disparar o tooltip
            MouseEvent phantom = new MouseEvent(
                    BremoverCliente,
                    MouseEvent.MOUSE_MOVED,
                    System.currentTimeMillis(),
                    0,
                    0,
                    0,
                    0,
                    false);
            ToolTipManager.sharedInstance().mouseMoved(phantom);
        } else {
            // Limpa o tooltip se uma linha estiver selecionada
            BremoverCliente.setToolTipText(null);
        }

        ctm.removeSelectedRows(clienteTable);

    }//GEN-LAST:event_BremoverClienteActionPerformed

    private void BlimparClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlimparClienteActionPerformed
        ctm.limpaTabela();
    }//GEN-LAST:event_BlimparClienteActionPerformed

    private void BatualizarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BatualizarClienteActionPerformed

        if (clienteTable.getSelectedRowCount() == 1) {
            String nome = TFnome.getText();
            String sobrenome = TFsobrenome.getText();
            String rg = TFrg.getText();
            String cpf = TFcpf.getText();
            String endereco = TFendereco.getText();
            int row = clienteTable.getSelectedRow();
            ctm.setValueAt(nome, row, 0);
            ctm.setValueAt(sobrenome, row, 1);
            ctm.setValueAt(rg, row, 2);
            ctm.setValueAt(cpf, row, 3);
            ctm.setValueAt(endereco, row, 4);
            Cliente cliente = ctm.getListaClientes().get(row);
            rep.updateRowCliente(row, ctm.getListaClientes().get(row));

        }
    }//GEN-LAST:event_BatualizarClienteActionPerformed

    private void BincluirVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BincluirVeiculoActionPerformed
        Marca marca = (Marca) Cmarca.getSelectedItem();
        Estado estado = (Estado) Cestado.getSelectedItem();
        Locacao locacao = null;
        Categoria categoria = (Categoria) Ccategoria.getSelectedItem();
        //valor de compra
        String str = FTFvalorDeCompra.getText();
        double valorDeCompra = 0;
        try {
            if (str != null && !str.isEmpty()) {
                valorDeCompra = Double.parseDouble(str);
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Por favor, insira um número válido.");
        }

        String placa = FTFplaca.getText();
        //ano
        String str0 = FTFano.getText();
        int ano = 0;
        try {
            if (str0 != null && !str0.isEmpty()) {
                ano = Integer.parseInt(FTFano.getText());
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Por favor, insira um número válido.");
        }

        //model,contructors,adding
        if ("Motocicleta".equals(Ctipo.getSelectedItem())) {
            ModeloMotocicleta modeloMoto = (ModeloMotocicleta) Cmodelo.getSelectedItem();
            Motocicleta motocicleta = new Motocicleta(marca, estado, locacao, categoria, valorDeCompra, placa, ano, modeloMoto);
            SwingUtilities.invokeLater(() -> {
                lvtm.addMotocicleta(motocicleta);
            });

        } else if ("Automóvel".equals(Ctipo.getSelectedItem())) {
            ModeloAutomovel modeloAuto = (ModeloAutomovel) Cmodelo.getSelectedItem();
            Automovel automovel = new Automovel(marca, estado, locacao, categoria, valorDeCompra, placa, ano, modeloAuto);
            lvtm.addAutomovel(automovel);
        } else if ("Van".equals(Ctipo.getSelectedItem())) {
            ModeloVan modeloVan = (ModeloVan) Cmodelo.getSelectedItem();
            Van van = new Van(marca, estado, locacao, categoria, valorDeCompra, placa, ano, modeloVan);
            lvtm.addVan(van);
        }
        FTFvalorDeCompra.setText("");
        FTFplaca.setText("");
        FTFano.setText("");

    }//GEN-LAST:event_BincluirVeiculoActionPerformed

    private void PveiculosComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_PveiculosComponentShown
        // Cmarca.setModel(cm.getMarcaModel());
        //Ccategoria.setModel(cm.getCategoriaModel());

    }//GEN-LAST:event_PveiculosComponentShown

    private void TFcpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFcpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFcpfActionPerformed

    private void CtipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CtipoActionPerformed
        if ("Motocicleta".equals(Ctipo.getSelectedItem().toString())) {
            Cmodelo.setModel((DefaultComboBoxModel) cm.getMotocicletaModel());
        } else if ("Automóvel".equals(Ctipo.getSelectedItem().toString())) {
            Cmodelo.setModel((DefaultComboBoxModel) cm.getAutomovelModel());
        } else if ("Van".equals(Ctipo.getSelectedItem().toString())) {
            Cmodelo.setModel((DefaultComboBoxModel) cm.getVanModel());
        }
    }//GEN-LAST:event_CtipoActionPerformed

    private void CmodeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmodeloActionPerformed

    }//GEN-LAST:event_CmodeloActionPerformed

    private void CmarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CmarcaActionPerformed

    private void veiculoTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_veiculoTableMousePressed
        JTable table = (JTable) evt.getSource();
        Point p = evt.getPoint();
        int row = table.rowAtPoint(p);
        if (evt.getClickCount() == 2) {
            // Your code here
        }
    }//GEN-LAST:event_veiculoTableMousePressed

    private void BvansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BvansActionPerformed
        lvtm.setTipoVeiculo(1);
        lvtm.setListaVeiculos();
    }//GEN-LAST:event_BvansActionPerformed

    private void BmotocicletasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BmotocicletasActionPerformed
        lvtm.setTipoVeiculo(2);
        lvtm.setListaVeiculos();
    }//GEN-LAST:event_BmotocicletasActionPerformed

    private void BautomoveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BautomoveisActionPerformed
        lvtm.setTipoVeiculo(3);
        lvtm.setListaVeiculos();
    }//GEN-LAST:event_BautomoveisActionPerformed

    private void CcategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CcategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CcategoriaActionPerformed

    private void jPanel3ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel3ComponentShown
        ClienteLocacaoTableModel modeloTabela = (ClienteLocacaoTableModel) clienteLocacaoTable.getModel();
        modeloTabela.filtrarClientes("");
    }//GEN-LAST:event_jPanel3ComponentShown

    private void CmarcaVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmarcaVeiculosActionPerformed
        Marca marca = (Marca) CmarcaVeiculos.getSelectedItem();
        f.filtrarPorMarca(marca.name());
    }//GEN-LAST:event_CmarcaVeiculosActionPerformed

    private void CcategoriaVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CcategoriaVeiculosActionPerformed
        Marca marca = (Marca) CcategoriaVeiculos.getSelectedItem();
        f.filtrarPorMarca(marca.name());
    }//GEN-LAST:event_CcategoriaVeiculosActionPerformed

    private void TFpesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFpesquisaKeyReleased
        String textoPesquisa = TFpesquisa.getText();
        filtrarPesquisa(textoPesquisa);
    }//GEN-LAST:event_TFpesquisaKeyReleased

    private void TFpesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFpesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFpesquisaActionPerformed

    private void BlocarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlocarActionPerformed
        //setComVeiculoLocado
        Cliente c = null;
        int lscliente = clienteLocacaoTable.getSelectedRow();
        if (lscliente != -1) {
            Cliente clienteSelecionado = rep.getListaClientes().get(lscliente);
            clienteSelecionado.setComVeiculoLocado(true);
            c = clienteSelecionado;
        }

        int dias = Integer.parseInt(TFdiasLocacao.getText());
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy"); // Altere para o formato da sua data
        Date dataDate;
        try {
            dataDate = formato.parse(FTFdataLocacao.getText());
        } catch (ParseException e) {
            e.printStackTrace();
            return;
        }
        Calendar data = Calendar.getInstance();
        data.setTime(dataDate);

        locarVeiculo(dias, data, c);

    }//GEN-LAST:event_BlocarActionPerformed

    private void VendaTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VendaTableMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_VendaTableMousePressed

    private void CcategoriaVeiculosVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CcategoriaVeiculosVendaActionPerformed
        Marca marca = (Marca) CcategoriaVeiculosVenda.getSelectedItem();
        f1.filtrarPorMarca(marca.name());
    }//GEN-LAST:event_CcategoriaVeiculosVendaActionPerformed

    private void CmarcaVeiculosVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmarcaVeiculosVendaActionPerformed
        Marca marca = (Marca) CmarcaVeiculosVenda.getSelectedItem();
        f1.filtrarPorMarca(marca.name());
    }//GEN-LAST:event_CmarcaVeiculosVendaActionPerformed

    private void BautomoveisVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BautomoveisVendaActionPerformed
        vvtm.setTipoVeiculo(3);
        vvtm.setListaVeiculos();
    }//GEN-LAST:event_BautomoveisVendaActionPerformed

    private void BmotocicletasVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BmotocicletasVendaActionPerformed
        vvtm.setTipoVeiculo(2);
        vvtm.setListaVeiculos();
    }//GEN-LAST:event_BmotocicletasVendaActionPerformed

    private void BvansVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BvansVendaActionPerformed
        vvtm.setTipoVeiculo(1);
        vvtm.setListaVeiculos();
    }//GEN-LAST:event_BvansVendaActionPerformed

    private void DevolverTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DevolverTableMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_DevolverTableMousePressed

    private void BvansDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BvansDevolverActionPerformed
        vdtm.setTipoVeiculo(1);
        vdtm.setListaVeiculos();
    }//GEN-LAST:event_BvansDevolverActionPerformed

    private void BmotocicletasDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BmotocicletasDevolverActionPerformed
        vdtm.setTipoVeiculo(2);
        vdtm.setListaVeiculos();
    }//GEN-LAST:event_BmotocicletasDevolverActionPerformed

    private void BautomoveisDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BautomoveisDevolverActionPerformed
        vdtm.setTipoVeiculo(3);
        vdtm.setListaVeiculos();
    }//GEN-LAST:event_BautomoveisDevolverActionPerformed

    private void FTFdataLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FTFdataLocacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FTFdataLocacaoActionPerformed

    private void jPanel4ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel4ComponentShown

    }//GEN-LAST:event_jPanel4ComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BatualizarCliente;
    private javax.swing.JButton Bautomoveis;
    private javax.swing.JButton BautomoveisDevolver;
    private javax.swing.JButton BautomoveisVenda;
    private javax.swing.JButton BincluirCliente;
    private javax.swing.JButton BincluirVeiculo;
    private javax.swing.JButton BlimparCliente;
    private javax.swing.JButton BlistarCliente;
    private javax.swing.JButton Blocar;
    private javax.swing.JButton Bmotocicletas;
    private javax.swing.JButton BmotocicletasDevolver;
    private javax.swing.JButton BmotocicletasVenda;
    private javax.swing.JButton BremoverCliente;
    private javax.swing.JButton Bvans;
    private javax.swing.JButton BvansDevolver;
    private javax.swing.JButton BvansVenda;
    private javax.swing.JComboBox<Categoria> Ccategoria;
    private javax.swing.JComboBox<Categoria> CcategoriaVeiculos;
    private javax.swing.JComboBox<Categoria> CcategoriaVeiculosVenda;
    private javax.swing.JComboBox<Estado> Cestado;
    private javax.swing.JComboBox<Marca> Cmarca;
    private javax.swing.JComboBox<Marca> CmarcaVeiculos;
    private javax.swing.JComboBox<Marca> CmarcaVeiculosVenda;
    private javax.swing.JComboBox<Object> Cmodelo;
    private javax.swing.JComboBox<String> Ctipo;
    private javax.swing.JTable DevolverTable;
    private javax.swing.JFormattedTextField FTFano;
    private javax.swing.JFormattedTextField FTFdataLocacao;
    private javax.swing.JFormattedTextField FTFplaca;
    private javax.swing.JFormattedTextField FTFvalorDeCompra;
    private javax.swing.JLabel Lano;
    private javax.swing.JLabel Lcategoria;
    private javax.swing.JLabel LdataLocacao;
    private javax.swing.JLabel Lestado;
    private javax.swing.JLabel Lmarca;
    private javax.swing.JLabel Lmodelo;
    private javax.swing.JLabel LnumDiasLocacao;
    private javax.swing.JLabel LpesquisarClientes;
    private javax.swing.JLabel Lplaca;
    private javax.swing.JLabel Ltipo;
    private javax.swing.JLabel LvalorDaCompra;
    private javax.swing.JPanel Pveiculos;
    private javax.swing.JFormattedTextField TFcpf;
    private javax.swing.JFormattedTextField TFdiasLocacao;
    private javax.swing.JTextField TFendereco;
    private javax.swing.JTextField TFnome;
    private javax.swing.JTextField TFpesquisa;
    private javax.swing.JFormattedTextField TFrg;
    private javax.swing.JTextField TFsobrenome;
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JTable VendaTable;
    private javax.swing.JTable clienteLocacaoTable;
    private javax.swing.JTable clienteTable;
    private javax.swing.JLabel cpfCliente;
    private javax.swing.JLabel enderecoCliente;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel nomeCliente;
    private javax.swing.JLabel rgCliente;
    private javax.swing.JLabel sobrenomeCliente;
    private javax.swing.JPanel tabCliente;
    private javax.swing.JTable veiculoTable;
    // End of variables declaration//GEN-END:variables

    public void initView() {

        java.awt.EventQueue.invokeLater(() -> {
            new Frame().setVisible(true);
        });
    }

    private void filtrarPesquisa(String textoPesquisa) {
        ClienteLocacaoTableModel modeloTabela = (ClienteLocacaoTableModel) clienteLocacaoTable.getModel();
        modeloTabela.filtrarClientes(textoPesquisa);
    }

    private void locarVeiculo(int dias, Calendar data, Cliente cliente) {
        int t = lvtm.getTipoVeiculo();
        int veiculoSelecionado = veiculoTable.getSelectedRow();

        switch (t) {
            case 1 -> {
                if (veiculoSelecionado != -1) {
                    Van v = rep.getListaVans().get(veiculoSelecionado);
                    v.locar(dias, data, cliente);
                }
            }
            case 2 -> {
                if (veiculoSelecionado != -1) {
                    Motocicleta m = rep.getListaMotocicletas().get(veiculoSelecionado);
                    m.locar(dias, data, cliente);
                }
            }
            case 3 -> {
                if (veiculoSelecionado != -1) {
                    Automovel a = rep.getListaAutomoveis().get(veiculoSelecionado);
                    a.locar(dias, data, cliente);
                }
            }
        }

    }

}
